apiVersion: v1
data:
    secret-key: ENC[AES256_GCM,data:Z1drKigUG3vPEBWL2gNX0v4Sn//S4cGxJsLRoRgLTS9iLtNNuYI4Odin3XeTnXlvuJ7vtqrl5NplN+JYHuhNz1KE225HIB+CZKMgU8jC2vbFXePLOFraUmW4clIuvw460CRdTczK2C2Xb1frfOWqvVW6MPc=,iv:TnBC2z9FVJ+r5SbJZL3V/0Ra6xXSfLzlw6HaGkPvkFg=,tag:HddHenlWTXtZvICVO4fSdw==,type:str]
kind: Secret
metadata:
    name: paperless-secret-key
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa3dPVHJKWVgvQzZLMlAv
            cW1vY0pqait5UzhLZ2dpbmFWSkFIQURxVUFRCmR6blQ3M1l3eHZrSnlKRHl4SDNz
            d25vRVFHVUpCKytXMGRZTEZvYkVMTFEKLS0tIFVOZndEUzI3RXZSTXR4SlV4WW1x
            T1FFazh1MnI1N3lWUU5EWGpxdy9XOGsKDqPDG2xgabl+8x3VGwJhyx7SRLHU3v3J
            md9730CJRBY55hQd+vZcJaWq8eWp0IgPlOWmhew4qy3CccrYNQVAsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzamtpL1RZWVZQUlIwWW8y
            WVN0a3JPNy9uU0E5MXp6VW9HTHRxRXJycDAwCnkreXphb0t6bjJTWm5OM0FxR0Fz
            OEN2bHJoZ1NoK2UxWnp1bktUVkpuM2sKLS0tIHQzaUxVS25lbTZTWTNHYXVKWEZD
            VlkzTUdseGcvUDdUbWxkVGNhUjIwZ1UKs9PHgdw5pMSluMFsNzjcFgdiIf3OlBVr
            Ijo3U8ClB/n/7RPIovQ9MBw+CkHrqg4pGWZo2UzMV0LUIU5QfcOmoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUmpyRTEwblhvVW41Q3Q5
            d0M5ck5WcWlIckxrQm5UUzE4b1pFekVwZGhnCkcrRTdoUVloeU0zSmxKRjZaOXEx
            V1hyVHNpSGxvdVZHUVVyeElhWW95elUKLS0tIHlZSnIrNitlT3hXU2NnN1R4YUZw
            UGVOSENHRFM0MTFOV1VBSjNxUDdwSHcKM5cSlApq+dGIPnsfm70F2SYugmxjZoLU
            +9nG/PEWHb6NzUUsPg3plQZtbby+zdqvabc8uUgv6o/WrlhRQ1c8PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
    encrypted_regex: (^data|stringData)$
    lastmodified: "2026-08-10T16:39:05Z"
    mac: ENC[AES256_GCM,data:SivLz7hxRwv89UncNHvl43618U6tsztd9jhMKHsuM/cFUdBI+mo6WgldAvBwtN5ugioCzeF/8Tnv4JCopY4XI3IKOiv5DpZTnJ5CmRIfNg1vnCqUPlj+BPnLKjnHkXOdayKaTn0Z7b3rbjViMQPnQvQAa5voFC2DH/pkGr/43wY=,iv:P5lvZflRJRCU6iE2ANuabFw8S8HxM8nYValuYcT7HzY=,tag:oP6gO1RVSSqMZxxdKA9Egg==,type:str]
    version: 3.13.3
