apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-auth
stringData:
    #ENC[AES256_GCM,data:6KOi8Gkz6eNYg44r68xHkiuMS9f1lbJRoMrlKGzb1ttpEzsyaiHQtXN3dJuZnAhMGdLlY5JYAlY0gWgcpThuscrygg==,iv:XuT6tOq+n0GtiM516sELGHeQ7ja3j8Awq5r5G4v29NY=,tag:3em3dT+9ilIBvWneYN+kgQ==,type:comment]
    auth.yml: ENC[AES256_GCM,data:cnpwxQCI8ohPV6v9WV1Onlptm/8QLZOqo++1zx+UHI9ziLmRQUZgzSRbe2Ra7iwrQKTWQLWHqhRAKPHvsotCN6ILpQDddcoV767EqptV2cZYxA2Vo+uEJ7Vq0vwcOjzJv9tAHCiuEdXxMY1bdXFoH68GC14R+7kutgGOhFvHkqBlgLsOyd7V2+1WBgNy4+utZsnRRuJAj61+zMFX2+Xg719F73uWHBKjZQ1aaapRRb9yey3xdg==,iv:wg8fJky9Og8jvjx4e3LwFydB73OM7NM0Pw/OCwPg9/Q=,tag:t5aVgy1TnmeebhG6HeB56w==,type:str]
    #ENC[AES256_GCM,data:DlOT9iZ0TPP2ypBCli7LVdI50jUD27MfFN8EqjTTbkmjgvUE2w==,iv:FHqsNgekxW5URna2xHMLQmdQXVodYm84mvtBB8XYgkc=,tag:Vi7+pZbJeCpvwu+wNFOulQ==,type:comment]
    #ENC[AES256_GCM,data:l8B5ZEiBkv/i5J3WsHu48TUdG6aJ5ZJR3Kc6xjoEXhTAm205BDs6Ctna9sZilLdoziQo9DrhRvLEwPElh9qARqr3X8GOWCE=,iv:ByCSsrGfriXBXvk0DfxnA0cQS4DdESXJwoPe38whVfE=,tag:AvihAp+R50oWSTU2PBVCmw==,type:comment]
    #ENC[AES256_GCM,data:g7IT9NoxIhaYOvo42up+slueLU4wFvXDe/Gxw+OCeTkrlqPB25+5zxcDSud2jjELPZJkZS+VbyFx+8T62MqR8YkmGxfF97Gd,iv:Nhd4KOEOn4ywO6b8U9niDBcwL3fjB8jNRMSNsEZSPss=,tag:K34jvA96M/QE3a3sWboDiA==,type:comment]
    #ENC[AES256_GCM,data:8s3dvScvg1lBU6N5EtjBrHjFb58Q2NcU4S4jBzn8Dg==,iv:ku7wwdNBF0sfU8BCf8dyaSLTIaXEgZcUURzCQiI14TE=,tag:wLZOSLRTe+ytV3feleyr6Q==,type:comment]
    webhook-password: ENC[AES256_GCM,data:Hnm9KITvsDMemu4FpZPm57/HP0+hXzqHmpO7Rw==,iv:HHL352A4Qu85uKIJ3myw/SLJYWt4rka9SXGKDAGeRms=,tag:q79i+emvxxpgQpTsM4nd+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMUtPRHhib2NSTHdMZW5H
            d3JiUHNuS2VoT1BXTHVNUG84MURsRkwrZEJzCnRPNGJVY0RyN282WWxUQTd5OEc0
            Q2U2aU1yaUZOckF4MzJXS2wwSExOMjQKLS0tIDQwZVkxTW5DcFJUWVltUnNtM2Vr
            MjVObEtXME1kazJMNGFRMUFYMFlhL2cK4DVK8AyziffulEzTtZ3ufgwP594QDUSF
            mVo8p08ajYkHtkgnqdRNLQD7juCTKP7pvokR6zNW2mxqjpwSGKdQ6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N1c4ZGFvbTk1ck5IcE5V
            Wlh4T1lZRHVaTytwY1hVSjU3anMyakUzekVrClEyc2V2c3dmM2N4RHoycDFQeWxK
            SU1CWWR3TGNTSG5hRkFjWkJhb25pdmsKLS0tIHp5elI1U3lvdWZNTlJSRHVnRkhh
            TDBycjFyNHpyN1NxMzRlOXlnNEtjbTgKIlhgp0D/j/7SgKoYKYFxYkGSerJtFz3q
            gsYNaGVv5ftIh9GyHr7k9FZLoDEtHGrFG+Rzkt1j+96F6LPvPuq+9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OUN6ZEFmZm5kY2EzRGZq
            N01oZXFzcnNkWFJ2cHVOQWw2eC82cUQ2NVYwCjQvYnAwL0FzUE9pNmxhOG5lUTkw
            MStEMUo0Y0huZXpHbkREZFN4SjlJNDQKLS0tIERmWWRPbXdKNjF0alhpVEUzOG9u
            LzJ1ZE9FVDBKd0x0czkrNkVNZm80V3MKhpWWOTZ1ELZQ7BeBtDGFLsr736vVnUdf
            hIZiw47gU8TRwRDER9OihfEYA5g2NI+a7IvTIbNbWVavrvwu0fAkPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
    encrypted_regex: (^data|stringData)$
    lastmodified: "2026-09-18T08:56:15Z"
    mac: ENC[AES256_GCM,data:ESVc5D9VduCMW9Kjo3VxfJo1e10Wq8fophu/7DappDPr6FRuoBeOGnHURydxbEe9CDGUGEtUP/ViYTErVnN4ReHPstgS5fNzDPXbxbnY+X/7a3kGJvcxNjQvGPfvnifJCsaYSjnYEYU/9r6H68xGafrQP6wgztOYGI4zSpQd+10=,iv:hjTjOt2VZVM5NZQ+vLPbTvli9Jhv8fF33jgd/07GMhs=,tag:8jUybNA42rtVCYk8vFeI9w==,type:str]
    version: 3.13.3
