apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-auth
stringData:
    auth.yml: ENC[AES256_GCM,data:a0qhcAqdXzJn6xCkUhpdyXJzUUiqA+lVO00dXbrNJ7xlz41b/fyq7S0fPbAzyS8MNmLfmqS1X4WB,iv:ylNuQRpVtMbbD/nf9bvKenmJlOIse5SFr18k9YQ68Kk=,tag:D0XbC7bU4XUmjckhF8Imjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWmRYZVptVUgwWGhpMFlq
            SWNweFRNQlJCODVWc2pIZ2Z3WjhJM2E5akhFCmxJV2M0UGtxejZTeHNYN2sya0dH
            emo2dmhMWUZOTGRsSTQ1TXFXMFBXcEUKLS0tIE9NQnFYbHBkYWh4R3RpSmhaaENv
            cnFrK3FTOTJSVGdCZmlhVjd3b3JvbzQKHT9lITqZ2WfMeYniFqIK5ApQWRkY66VR
            Ozh8pF5wgIKmiw4MvbvsUavmITo8+N4HMScXttXD3OQ0TLo7LtJzpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sqcyumdyut9t3e4557wxawwnvxlqt7wsprtfzgdzw984nlf5jsnqxsyv8z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCckRYOVAyQ3FTV1piRHVL
            WThBblc1SmFTYndkT0M1SHNNeFcreWtFaVdnCkl0S1V2QmQ3UTFaRXpXQlhIVDhC
            VUUzemVkVDROcjkxR3NqZ1VsbHFubU0KLS0tIEF1YlNtM245RkoxN0dsZVdKOWEv
            eU1XZUs3bG44VU5Wemc0ejd1SkN6NXcKIOgJNt8Smfg9rQzeYO6ExAWjLwtPgbH3
            YTX0FoGdQNVyUDdTqFZqGgDUqhtDvBnH4jb5bg2WPcYkAJ7cB+Egzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wk95zsslqpulwrvuywuhpza0h0gpwzwxq04f536at67p50ec4g5sex6g9r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eGFHYkgwWFJFRDA4ZXZQ
            MHdtOUsvazdnNTNEYnIwNjdsZmhPeEdBczBBClpsWjVvcmRRcUZST1hWdytSTHov
            SFJncXlXUkdNWWZYRjAvL3dQaHVaU28KLS0tIGtXQVlXWUNLS1pYbGZzL01PWDVB
            cTJ0ckdOZHBzT01tWW5RSU9mQmdvMGsKAj3G92H76MVyaxfaS/JC3ifTc0B0hl3Y
            OerBSCqy/YMCExU80RVfVpkZQ3Up5KrUV+L3vWFEaepeCDOUgQMdIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18uhtqch7u93g56mqehhtp3nxvhhf0mq9tpqqdlvqu28hluxy5d4s4jampd
    encrypted_regex: (^data|stringData)$
    lastmodified: "2026-09-18T08:30:16Z"
    mac: ENC[AES256_GCM,data:UjYRNdms3zTtoFQGSVqk7EUZI7uTOXf0jGj52IbMCyA4M7ant78/YwAi53cMB2mLdleyT7D6imtJ1Is9chsdyuBUbO2/MlBd+6VLqkZfxuKhASkCDbeV1890twz3FwyxAlwKlJqLwx3qXgN6YecpUL3vwx0KgwJeKbz89oJKjwk=,iv:yoyTAeO2FXvzwj4DerTgl2U2iehII4NLWU4lTD0EPMw=,tag:BkGskiw2ejot/O+p9KMshg==,type:str]
    version: 3.13.3
